Product
Product-Every-Day/product-everyday-admin pull request #7
Opened 2024-02-02 13:47 UTC by Piyushg094

2024-02-04 15:24 UTC, subhamsahu commented on admin-ui/src/app/pages/Category/Category.js
> +  console.log("piyush")
Remove these kinds of unnecessary logging

2024-02-04 15:40 UTC, Piyushg094 commented
Ohky sir

On Sun, Feb 4, 2024, 8:54 PM subhamsahu ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In admin-ui/src/app/pages/Category/Category.js
> <https://github.com/Product-Every-Day/product-everyday-admin/pull/7#discussion_r1477343300>
> :
>
> > @@ -26,6 +27,9 @@ const CategoryList = () => {
>    const [dialogOpen, setDialogOpen] = useState(false);
>    const [bulkaction, setbulkaction] = useState(null)
>
> +  console.log("piyush")
>
> Remove these kinds of unnecessary logging
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Product-Every-Day/product-everyday-admin/pull/7#pullrequestreview-1861460004>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWOZEPVQUUJQKO6NRZO6WDDYR6R37AVCNFSM6AAAAABCWW2TY2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRRGQ3DAMBQGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-02-05 14:22 UTC, subhamsahu commented on admin-ui/src/app/pages/Category/components/CategoryCreateForm.js
> +    //     if (selectedFiles && selectedFiles.length>0) {
Remove Unnecessary Function

2024-02-05 14:24 UTC, subhamsahu commented on admin-ui/src/app/pages/Product/components/CreateForm.js
> +
Remove

2024-02-05 14:25 UTC, subhamsahu commented on admin-ui/src/app/pages/Product/components/CreateForm.js
> +          setSelectedCategory(e.target.value)
2 Condtions , use elif

2024-02-05 14:25 UTC, subhamsahu commented on admin-ui/src/app/pages/Product/components/CreateForm.js
> +            console.log(selectedCategoryData)
Unnecssary code

2024-02-05 14:26 UTC, subhamsahu commented on admin-ui/src/app/pages/Product/components/CreateForm.js
> +                {/* <Grid item xs={4}>
If possible , remove unwanted code

2024-02-05 14:27 UTC, subhamsahu commented on admin-ui/src/app/services/Common.js
> -    return data
Check if unwanted comment

2024-02-05 14:27 UTC, subhamsahu commented on server/app/controllers/category.js
> +const count = async (req, res) => {
chnage count to list

2024-02-05 14:28 UTC, subhamsahu commented on server/app/controllers/product.js
> +        // if(!category){
Revert and show the error

2024-02-05 14:29 UTC, subhamsahu commented on server/app/public/images/images-1706187664424-995346249.jpeg
Put some generic image

2024-02-05 14:30 UTC, subhamsahu commented on server/app/routes/api/category.js
> +router.get('/count', async (req, res) => {
change from count to list

2024-02-05 14:30 UTC, subhamsahu commented on server/app/routes/api/category.js
> +// count categories
remove if unnecessary

2024-02-05 14:30 UTC, subhamsahu commented on server/app/routes/api/razorpay.js
> +// ?const razorpayController = require('../../controllers/razorpay')
Revert and show me error

2024-02-05 14:32 UTC, subhamsahu requested changes
Apply all changes

2024-02-06 05:41 UTC, subhamsahu approved these changes

2024-02-06 05:41 UTC, merged